// Pixelikonerna (16×16, ett pixelkorn) i spelets stil – mörk, färgad kontur, 3–4 toner – i stället för emoji.
// Carl ville ha pixlade ikoner i stället för färdiga emojis. Ikonerna ritades för menyförslaget (artefakten
// "Pixelstadens nya meny") och används av mobilen (js/core/mobilen.js). Kartorna: en bokstav per pixel ur PAL,
// punkt eller mellanslag = genomskinligt.
//   ikonURL(namn)  → dataURL (16×16, skalas upp med image-rendering: pixelated)
export const PAL = {
  k: '#1e1a24', w: '#f4f1ea', W: '#ffffff', g: '#c8c4cf', G: '#7d7689', d: '#4a4452',
  y: '#ffd23f', Y: '#d19a1c', o: '#f08a2a', r: '#e04848', R: '#9e2a2e',
  b: '#4a8de0', B: '#2a5aa8', c: '#a8d4ff', n: '#52b464', N: '#2f7a3e', l: '#9be08a',
  s: '#f1c7a3', S: '#d89a72', E: '#6e4426', h: '#7a4a2a', j: '#a8703e', H: '#4a2c18',
  p: '#ff9cc4', P: '#d0507e', t: '#e2b47a', T: '#a8733f', u: '#9a6ad8', U: '#6a3ab0',
  D: '#a0643c',
};
export const KARTOR = {
  telefon: [
    '................',
    '....kkkkkkkk....',
    '...kgwwwwwwgk...',
    '...kwkkkkkkGk...',
    '...kwkcbbbbGk...',
    '...kwkcnbybGk...',
    '...kwkbbbbbGk...',
    '...kwkbrbubGk...',
    '...kwkbbbbbGk...',
    '...kwkbybnbGk...',
    '...kwkbbbbBGk...',
    '...kwkkkkkkGk...',
    '...kgGGkkGGGk...',
    '...kGGGGGGGdk...',
    '....kkkkkkkk....',
    '................'],
  meny: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwgk..',
    '..kkkkkkkkkkkk..',
    '................',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwgk..',
    '..kkkkkkkkkkkk..',
    '................',
    '..kkkkkkkkkkkk..',
    '..kwwwwwwwwwgk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................'],
  karta: [
    '................',
    '................',
    '.kkkkk.kkkk.kkk.',
    '.kllnkkcccckklk.',
    '.klnnNkcbcckllk.',
    '.kllnNkccbckrrk.',
    '.kyllNkcccckrRk.',
    '.klyllkcbcckkrk.',
    '.kllyyycccyylk..',
    '.kllnlkcbcckllk.',
    '.klnnNkcccckllk.',
    '.kllNlkccbckllk.',
    '.kkkkk.kkkk.kkk.',
    '................',
    '................',
    '................'],
  taxi: [
    '................',
    '......kkkk......',
    '......kyYk......',
    '.....kkkkkk.....',
    '....kccbbcck....',
    '...kcckbbkcck...',
    '..kkkkkkkkkkkk..',
    '.kyyyyyyyyyyyYk.',
    '.kWyyykkkkyyWYk.',
    '.kyyyykwkkyyyYk.',
    '.kYYYYYYYYYYYYk.',
    '.kkddkkkkkkddkk.',
    '..kGGk....kGGk..',
    '...kk......kk...',
    '................',
    '................'],
  kompisar: [
    '................',
    '....kkk.........',
    '...kSSSk..kkk...',
    '...ksssk.kSSSk..',
    '...ksssk.ksssk..',
    '....kkk..ksssk..',
    '..kkbbbkk.kkk...',
    '.kbbbbBbbkkrrkk.',
    '.kbcbbbBbkrrrRrk',
    '.kbbbbbBbkrprrRk',
    '.kbbbbbBbkrrrrRk',
    '.kkkkkkkkkrrrrRk',
    '..........kkkkkk',
    '................',
    '................',
    '................'],
  chatt: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kwwkkwkkwkkwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kwwkkkwkkwwwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kgwwwwwwwwwggk.',
    '..kkkkwwgkkkkk..',
    '.....kwgk.......',
    '.....kgk........',
    '.....kk.........',
    '................',
    '................'],
  rost: [
    '................',
    '......kkkk......',
    '.....kGggGk.....',
    '.....kgkkGk.....',
    '.....kGggGk.....',
    '.....kgkkGk.....',
    '.....kGggGk.....',
    '...k.kgggdk.k...',
    '...kk.kkkk.kk...',
    '....kk....kk....',
    '.....kkkkkk.....',
    '.......kk.......',
    '.......kk.......',
    '.....kkkkkk.....',
    '................',
    '................'],
  mal: [
    '................',
    '.....kkkkkk.....',
    '....krrrrrRk....',
    '...krwwwwwwRk...',
    '..krwwrrrrwwRk..',
    '..krwrwwwwrwRk..',
    '..krwrwrrwrwRk.k',
    '..krwrwrkkkkkkyk',
    '..krwrwwwwrwRkk.',
    '..krwwrrrrwwRk..',
    '...krwwwwwwRk...',
    '....kRRRRRRk....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................'],
  vecka: [
    '................',
    '...kk.....kk....',
    '..kkGkkkkkGkk...',
    '.krrrrrrrrrrRk..',
    '.kRRRRRRRRRRRk..',
    '.kwwwwwwwwwwgk..',
    '.kwkwkwkwkwwgk..',
    '.kwwwwwwwwwwgk..',
    '.kwkwkwkwbbwgk..',
    '.kwwwwwwwbbwgk..',
    '.kwkwkwkwkwwgk..',
    '.kgggggggggggk..',
    '.kkkkkkkkkkkkk..',
    '................',
    '................',
    '................'],
  dagbok: [
    '................',
    '..kkkkkkkkkkk...',
    '..kjhhhhhhhhjk..',
    '..kjhkkkkkhhjk..',
    '..kjhkwwwkhhjk..',
    '..kjhkkkkkhhjk..',
    '..kjhhhhhhhhjk..',
    '..kjhhhhhhhhjk..',
    '..kjhhyyhhhhjk..',
    '..kjhhyyhhhhjk..',
    '..kjHHHHHHHHjk..',
    '..kwwwwwwwwwgk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................'],
  ljud: [
    '................',
    '......kk........',
    '.....kGk...k....',
    '....kGgk....k...',
    '.kkkGggk.k...k..',
    '.kggggg k..k..k.',
    '.kgwggg k..k..k.',
    '.kggggg k..k..k.',
    '.kkkGggk.k...k..',
    '....kGgk....k...',
    '.....kGk...k....',
    '......kk........',
    '................',
    '................',
    '................',
    '................'],
  musik: [
    '................',
    '.........kkkkk..',
    '......kkkuuuuk..',
    '......kuuuUUuk..',
    '......kuUkkkuk..',
    '......kuk...uk..',
    '......kuk...uk..',
    '......kuk...uk..',
    '......kuk.kkuk..',
    '...kkkkuk.kuuk..',
    '..kuuUuuk.kUUk..',
    '..kuUUUUk.kkk...',
    '...kkkkk........',
    '................',
    '................',
    '................'],
  zoom: [
    '................',
    '....kkkkk.......',
    '...kcccWck......',
    '..kcWccccck.....',
    '..kcWccccck.....',
    '..kcccccccbk....',
    '..kcccccccbk....',
    '...kccccbbk.....',
    '....kkkkkkhk....',
    '.........khjk...',
    '..........khjk..',
    '...........khjk.',
    '............khk.',
    '.............k..',
    '................',
    '................'],
  nyheter: [
    '................',
    '.kkkkkkkkkkkk...',
    '.kwwwwwwwwwwk...',
    '.kwkkkkkkkkwkkk.',
    '.kwwwwwwwwwwkgk.',
    '.kwrrrwkkkwwkgk.',
    '.kwrrrwwwwwwkgk.',
    '.kwrrrwkkkwwkgk.',
    '.kwwwwwwwwwwkgk.',
    '.kwkkkkkkkkwkgk.',
    '.kwwwwwwwwwwkgk.',
    '.kwkkkkkkwwwkgk.',
    '.kgggggggggggkk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................'],
  kugge: [
    '................',
    '......kkkk......',
    '...kk.kggk.kk...',
    '..kggkkggkkggk..',
    '..kggggggggGgk..',
    '...kgggkkgggk...',
    '.kkkggk..kgGkkk.',
    '.kgggk....kgGGk.',
    '.kgggk....kGGGk.',
    '.kkkGGk..kGGkkk.',
    '...kgGGkkGGGk...',
    '..kgGGGGGGGGGk..',
    '..kGGkkGGkkGGk..',
    '...kk.kGGk.kk...',
    '......kkkk......',
    '................'],
  sprak: [
    '................',
    '.....kkkkkk.....',
    '...kkcblbbckk...',
    '..kcbllnbbbcbk..',
    '..kblllnbbblbk..',
    '.kcbbllnbbllnBk.',
    '.kbbbbnbbbllnBk.',
    '.kbbbbbbbllnbBk.',
    '.kbblnbbbbnbbBk.',
    '.kbbllnbbbbbbBk.',
    '..kbllnbbbbbBk..',
    '..kcbbbbbblBBk..',
    '...kkBBBBBBkk...',
    '.....kkkkkk.....',
    '................',
    '................'],
  drakt: [
    '................',
    '................',
    '..kkkkk..kkkkk..',
    '.kuuuuukkuuuuUk.',
    '.kuWuuuuuuuuuUk.',
    '.kuukkkuuukkkUk.',
    '.kuk...kuk...kk.',
    '.kuukkkuuukkkUk.',
    '.kuuuuuukuuuuUk.',
    '..kuuuuk.kuuUk..',
    '...kkkk...kkk...',
    '.......k........',
    '.......yk.......',
    '........yk......',
    '.........k......',
    '................'],
  cykel: [
    '................',
    '................',
    '................',
    '..........dkkd..',
    '...........G....',
    '.....HHHH..G....',
    '.......rrrrr....',
    '.......r...RR...',
    '...kkk.r..RkRk..',
    '..kG..kr.RkGR.k.',
    '.kG....rRkG.R..k',
    '.kG.grrrkkG.g..k',
    '.k.....k.k.....k',
    '..k...k...k...k.',
    '...kkk.....kkk..',
    '................'
  ],
  soffa: [
    '................',
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kbbbbbbbbbbk..',
    '..kbcbbbbbbbBk..',
    '.kkbbbbbbbbbBkk.',
    'kbbkBBBBBBBBkbbk',
    'kbcbbbbkbbbbbbBk',
    'kbbbbbbkbbbbbbBk',
    'kBBBBBBBBBBBBBBk',
    'kkhkkkkkkkkkkhkk',
    '..k..........k..',
    '................',
    '................',
    '................'],
  hem: [
    '................',
    '.......kk.......',
    '......krRk.kk...',
    '.....krrrRkkGk..',
    '....krrrrrRkGk..',
    '...krrrrrrrRkk..',
    '..kRRRRRRRRRRk..',
    '...kwwwwwwwgk...',
    '...kwccwkhkgk...',
    '...kwccwkhkgk...',
    '...kwwwwkhkgk...',
    '...kwwwwkyhgk...',
    '...kggggkhkgk...',
    '...kkkkkkkkkk...',
    '................',
    '................'],
  kompass: [
    '................',
    '......kkkk......',
    '....kkyyyykk....',
    '...kyywrwwyyk...',
    '..kywwwrRwwwYk..',
    '..kywwwrRwwwYk..',
    '.kywwwwrRwwwwYk.',
    '.kywGwwkRwwGwYk.',
    '.kywwwwgkwwwwYk.',
    '.kywwwwgGwwwwYk.',
    '..kywwwgGwwwYk..',
    '..kywwwgGwwwYk..',
    '...kYYwwwwYYk...',
    '....kkYYYYkk....',
    '......kkkk......',
    '................'
  ],
  ballong: [
    '................',
    '.....kkkkk......',
    '....krrrrrk.....',
    '...krWrrrrRk....',
    '...krWrrrrRk....',
    '...krrrrrrRk....',
    '...krrrrrRRk....',
    '....kRrrRRk.....',
    '.....kRRRk......',
    '......kRk.......',
    '.......k........',
    '......k.........',
    '.......k........',
    '......k.........',
    '................',
    '................'],
  burgare: [
    '................',
    '................',
    '....kkkkkkkk....',
    '...kttttttttk...',
    '..ktwtttwtttTk..',
    '..kttttwtttttk..',
    '..kTTTTTTTTTTk..',
    '..knlnlnlnlnNk..',
    '..khhhhhhhhhhk..',
    '..kHHHHHHHHHHk..',
    '..kyyyyyyyyyYk..',
    '..kttttttttttk..',
    '...kTTTTTTTTk...',
    '....kkkkkkkk....',
    '................',
    '................'],
  blixt: [
    '................',
    '........kkkk....',
    '.......kyyyk....',
    '......kyyyk.....',
    '.....kyyyk......',
    '....kyyyykkkk...',
    '...kyyyyyyyyk...',
    '...kkkkyyyyk....',
    '......kyyyk.....',
    '.....kyyyk......',
    '....kyyYk.......',
    '...kyYk.........',
    '...kYk..........',
    '...kk...........',
    '................',
    '................'],
  glad: [
    '................',
    '.....kkkkkk.....',
    '...kkyyyyyykk...',
    '..kyyyyyyyyyYk..',
    '..kyykyyyykyYk..',
    '.kyyykyyyykyyYk.',
    '.kyyyyyyyyyyyYk.',
    '.kyykyyyyyykyYk.',
    '.kyyykkkkkkyyYk.',
    '..kyyyyyyyyyYk..',
    '..kYyyyyyyyYYk..',
    '...kkYYYYYYkk...',
    '.....kkkkkk.....',
    '................',
    '................',
    '................'],
  // figurskaparen (js/core/figursteg.js) – ritade för förslaget "Ny start i Pixelstaden"; kropp = storleken
  penna: [
    '................',
    '...........kkk..',
    '..........kpppk.',
    '.........kpPPPk.',
    '........kgkPPk..',
    '.......kygGkk...',
    '......kyyYgk....',
    '.....kyyYYk.....',
    '....kyyYYk......',
    '...kyyYYk.......',
    '..ktyYYk........',
    '..kttYk.........',
    '.ktttk..........',
    '.kGkk...........',
    '.kk.............',
    '................'],
  hud: [
    '................',
    '.kkkkk...kkkkk..',
    'kwssssk.kwSSSSk.',
    'kssssSk.kSSSSDk.',
    'kssssSk.kSSSSDk.',
    'ksssSSk.kSSSDDk.',
    '.kkkkk...kkkkk..',
    '................',
    '.....kkkkk......',
    '....kwDDDDk.....',
    '....kDDDDEk.....',
    '....kDDDDEk.....',
    '....kDDDEEk.....',
    '.....kkkkk......',
    '................',
    '................'],
  frisyr: [
    '................',
    '.....kkkkkk.....',
    '...kkhhhhhhkk...',
    '..khhjhhhhhhhk..',
    '.khhjhhhhhhhhhk.',
    '.khjhhhhhhhhhHk.',
    '.khhssssssshhHk.',
    '.khsskssksssshk.',
    '.khsssssssssSHk.',
    '.kHssssssssSSHk.',
    '..kssssssssSSk..',
    '..ksssRRRsssSk..',
    '...kssssssSSk...',
    '....kkSSSSkk....',
    '......kkkk......',
    '................'],
  palett: [
    '................',
    '............kk..',
    '...........kTTk.',
    '..........kTttk.',
    '.........kTtTk..',
    '........kTtTk...',
    '.......kTtTk....',
    '......kgGGk.....',
    '.....kgWgGk..kk.',
    '....krrrGk..kbbk',
    '...kryrrk...kbBk',
    '..krrrrk.....kk.',
    '..krRrk..kk.....',
    '.kRRkk..kyyk....',
    '.kk......kYk....',
    '..........k.....'],
  ogon: [
    '................',
    '................',
    '................',
    '................',
    '..kkkkk..kkkkk..',
    '.kWWbbWkkWWbbWk.',
    '.kWbkkbkkWbkkbk.',
    '.kWbkWbkkWbkWbk.',
    '.kWWbbWkkWWbbWk.',
    '..kkkkk..kkkkk..',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................'],
  mun: [
    '................',
    '................',
    '................',
    '...kkk....kkk...',
    '..krrrk..krrrk..',
    '.krrWrrkkrrrrrk.',
    'krrWrrrrrrrrrrrk',
    'kRRRRRRRRRRRRRRk',
    '.kRrrrrrrrrrrRk.',
    '..kRrrrrrrrrRk..',
    '...kkRRRRRRkk...',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
    '................'],
  troja: [
    '................',
    '...kkkk..kkkk...',
    '..kbbbbkkbbbbk..',
    '.kbbcbbbbbbbbBk.',
    'kbbcbbbbbbbbbbBk',
    'kbbbbbbbbbbbbBBk',
    'kbBBkbbbbbbkBBBk',
    '.kkkkbbbbbbkkkk.',
    '....kbcbbbbk....',
    '....kbbbbbBk....',
    '....kbbbbbBk....',
    '....kbbbbbBk....',
    '....kBBBBBBk....',
    '....kkkkkkkk....',
    '................',
    '................'],
  byxor: [
    '................',
    '...kkkkkkkkkkk..',
    '...kTTTTyyTTTk..',
    '...kbcbbbbbbBk..',
    '...kbcbbbbbbBk..',
    '...kbbbbkbbbBk..',
    '...kbbbkkbbbBk..',
    '...kbbbk.kbbBk..',
    '...kbbbk.kbbBk..',
    '...kbbbk.kbbBk..',
    '...kbbBk.kbBBk..',
    '...kbbBk.kbBBk..',
    '...kBBBk.kBBBk..',
    '...kkkkk.kkkkk..',
    '................',
    '................'],
  skor: [
    '................',
    '................',
    '................',
    '.......kkkkk....',
    '......kbbbbbk...',
    '.....kbkWkWbbk..',
    '....kbbbkbkbbbk.',
    '..kkbbbbbbbbbbk.',
    '.kbbbbbbbbbbbbk.',
    '.kbcbbbbbbbbbBk.',
    '.kwwwwwwwwwwwwk.',
    '.kgggggggggggggk',
    '..kkkkkkkkkkkkk.',
    '................',
    '................',
    '................'],
  bock: [
    '................',
    '.kkkkkkkkkkkkkk.',
    '.knnnnnnnnnnnnk.',
    '.knnnnnnnnnWWnk.',
    '.knnnnnnnnWWWnk.',
    '.knnnnnnnWWWnnk.',
    '.knWWnnnWWWnnnk.',
    '.knWWWnWWWnnnnk.',
    '.knnWWWWWnnnnnk.',
    '.knnnWWWnnnnnnk.',
    '.knnnnWnnnnnnnk.',
    '.kNNNNNNNNNNNNk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................'],
  tarning: [
    '................',
    '..kkkkkkkkkkkk..',
    '.kwWwwwwwwwwwwk.',
    '.kWkkwwwwwwwwgk.',
    '.kwkkwwwwwwwwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kwwwwwkkwwwwgk.',
    '.kwwwwwkkwwwwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kwwwwwwwwkkwgk.',
    '.kwwwwwwwwkkwgk.',
    '.kgggggggggggGk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................'],
  pilH: [
    '................',
    '...kk...........',
    '...kWkk.........',
    '...kWwwkk.......',
    '...kwwwwwkk.....',
    '...kwwwwwwwkk...',
    '...kwwwwwwwwwk..',
    '...kwwwwwwwwgk..',
    '...kwwwwwwgkk...',
    '...kwwwwgkk.....',
    '...kwwgkk.......',
    '...kgkk.........',
    '...kk...........',
    '................',
    '................',
    '................'],
  pilV: [
    '................',
    '...........kk...',
    '.........kkWk...',
    '.......kkwwWk...',
    '.....kkwwwwwk...',
    '...kkwwwwwwwk...',
    '..kwwwwwwwwwk...',
    '..kgwwwwwwwwk...',
    '...kkgwwwwwwk...',
    '.....kkgwwwwk...',
    '.......kkgwwk...',
    '.........kkgk...',
    '...........kk...',
    '................',
    '................',
    '................'],
  kropp: [
    '................',
    '......kkkk......',
    '.....khhhhk.....',
    '.....khsssk.....',
    '.....kssssk.....',
    '......kssk......',
    '....kkbbbbkk....',
    '...kbbbbbbbbk...',
    '...kbkbbbbkbk...',
    '...kskbbbbksk...',
    '....kkBBBBkk....',
    '.....kBBkBBk....',
    '.....kBBkBBk....',
    '.....kBBkBBk....',
    '....kkkkkkkkk...',
    '................'],
};
// mörka pilar för ljusa knappar (en vit pil på en vit knapp syns inte)
KARTOR.pilHm = KARTOR.pilH.map((r) => r.replace(/w/g, 'd').replace(/g/g, 'G'));
KARTOR.pilVm = KARTOR.pilV.map((r) => r.replace(/w/g, 'd').replace(/g/g, 'G'));
const CACHE = new Map();
export function ikonURL(namn) {
  if (CACHE.has(namn)) return CACHE.get(namn);
  const m = KARTOR[namn];
  if (!m || typeof document === 'undefined') return '';
  const c = document.createElement('canvas'); c.width = 16; c.height = 16;
  const g = c.getContext('2d');
  m.forEach((rad, y) => { for (let x = 0; x < 16; x++) { const col = PAL[rad[x]]; if (col) { g.fillStyle = col; g.fillRect(x, y, 1, 1); } } });
  const u = c.toDataURL();
  CACHE.set(namn, u);
  return u;
}
